### PR TITLE
Major refactor of command handling

### LINKED ISSUE #2: Simplify report output handling
The initial implementation of `gh-dependency-report` defaults to using standard out for the CSV report with progress / log being emitted via standard err.  This is a little confusing for anyone who hasn't looked at the usage statement or intrinsically know to redirect stdout.

```shell
andyfeller@Andrews-MacBook-Pro:andyfeller/gh-dependency-report ‹main*›$ go run main.go andyfeller
2022-01-28T08:09:58.099-0500	INFO	cmd/root.go:80	Processing repos: [andyfeller argo-cd argo-helm argocd-notifications bespoke branch-protection-enforcer-app chef codeql-action-configs docker-alpine-abuild docker.github.io docs dotfiles fabric8-pipeline-library gh-dependency-report integrations-core jenkins-openshift-login-plugin jenkins-pipeline-library linux mockserver my-py-grpc-repo openshift-cassandra openshift-sync-plugin populate-project powershell-poc private-stack python stacks-experiment]
2022-01-28T08:09:58.099-0500	DEBUG	cmd/root.go:122	Processing andyfeller/andyfeller
2022-01-28T08:09:58.261-0500	DEBUG	cmd/root.go:122	Processing andyfeller/argo-cd
2022-01-28T08:09:58.374-0500	DEBUG	cmd/root.go:122	Processing andyfeller/argo-helm
2022-01-28T08:09:58.489-0500	DEBUG	cmd/root.go:122	Processing andyfeller/argocd-notifications
2022-01-28T08:09:58.606-0500	DEBUG	cmd/root.go:122	Processing andyfeller/bespoke
2022-01-28T08:09:59.071-0500	DEBUG	cmd/root.go:143	Processing andyfeller/bespoke > .github/workflows/init.yml
2022-01-28T08:09:59.315-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/workflows/init.yml > actions/checkout
2022-01-28T08:09:59.315-0500	DEBUG	cmd/root.go:143	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json
2022-01-28T08:10:00.099-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > @actions/core
2022-01-28T08:10:00.099-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > @actions/github
2022-01-28T08:10:00.099-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > @actions/http-client
2022-01-28T08:10:00.099-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > @octokit/auth-token
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > @octokit/core
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > @octokit/endpoint
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > @octokit/graphql
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > @octokit/openapi-types
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > @octokit/plugin-paginate-rest
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > @octokit/plugin-rest-endpoint-methods
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > @octokit/request
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > @octokit/request-error
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > @octokit/types
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > argparse
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > before-after-hook
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > deprecation
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > handlebars
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > is-plain-object
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > js-yaml
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > minimist
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > neo-async
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > node-fetch
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > once
2022-01-28T08:10:00.100-0500	DEBUG	cmd/root.go:154	Processing andyfeller/bespoke > .github/actions/populate_project/package-lock.json > source-map
Owner,Repo,Manifest,Exceeds Max Size,Parseable,Package Manager,Dependency,Has Dependencies?,Requirements,License,License Url
andyfeller,bespoke,.github/workflows/init.yml,false,true,ACTIONS,actions/checkout,true,= 2,MIT,http://choosealicense.com/licenses/mit/
andyfeller,bespoke,.github/actions/populate_project/package-lock.json,false,true,NPM,@actions/core,true,= 1.6.0,MIT,http://choosealicense.com/licenses/mit/
andyfeller,bespoke,.github/actions/populate_project/package-lock.json,false,true,NPM,@actions/github,true,= 5.0.0,MIT,http://choosealicense.com/licenses/mit/
andyfeller,bespoke,.github/actions/populate_project/package-lock.json,false,true,NPM,@actions/http-client,true,= 1.0.11,NOASSERTION,http://choosealicense.com/licenses/other/
andyfeller,bespoke,.github/actions/populate_project/package-lock.json,false,true,NPM,@octokit/auth-token,true,= 2.5.0,MIT,http://choosealicense.com/licenses/mit/
andyfeller,bespoke,.github/actions/populate_project/package-lock.json,false,true,NPM,@octokit/core,true,= 3.5.1,MIT,http://choosealicense.com/licenses/mit/
andyfeller,bespoke,.github/actions/populate_project/package-lock.json,false,true,NPM,@octokit/endpoint,true,= 6.0.12,MIT,http://choosealicense.com/licenses/mit/
andyfeller,bespoke,.github/actions/populate_project/package-lock.json,false,true,NPM,@octokit/graphql,true,= 4.8.0,MIT,http://choosealicense.com/licenses/mit/
andyfeller,bespoke,.github/actions/populate_project/package-lock.json,false,true,NPM,@octokit/openapi-types,false,= 11.2.0,MIT,http://choosealicense.com/licenses/mit/
andyfeller,bespoke,.github/actions/populate_project/package-lock.json,false,true,NPM,@octokit/plugin-paginate-rest,true,= 2.17.0,NOASSERTION,http://choosealicense.com/licenses/other/
andyfeller,bespoke,.github/actions/populate_project/package-lock.json,false,true,NPM,@octokit/plugin-rest-endpoint-methods,true,= 5.13.0,MIT,http://choosealicense.com/licenses/mit/
andyfeller,bespoke,.github/actions/populate_project/package-lock.json,false,true,NPM,@octokit/request,true,= 5.6.2,MIT,http://choosealicense.com/licenses/mit/
andyfeller,bespoke,.github/actions/populate_project/package-lock.json,false,true,NPM,@octokit/request-error,true,= 2.1.0,MIT,http://choosealicense.com/licenses/mit/
```

Given we have support for the extension to write the report to a named file, we shall instead change the extension so it always writes output to a file.  The filename will be randomly generated if not provided, based on the current date/time more than likely.

```shell
andyfeller@Andrews-MacBook-Pro:andyfeller/gh-dependency-report ‹main*›$ go run main.go           
Error: requires at least 1 arg(s), only received 0
Usage:
  gh-dependency-report [flags] owner [repo ...]

Flags:
  -e, --exclude strings      Repositories to exclude from report
  -h, --help                 help for gh-dependency-report
  -o, --output-file string   Name of file to write CSV report, defaults to stdout
```

### PR DESCRIPTION
**Pull request by andyfeller**
These changes were being based on advice from @mislav for isolating the spf13/cobra and uber/zap logic from the core of the cli logic.

Now, the application should be easier to build better tests, being able to inject mocks appropriately as well as allowing for tests to run without blowing up due to log initialization problems.  That aspect is going to need more work, however, as I want to have a better default logging configuraiton with flags to override levels.

### CODE REVIEW

File: cmd/root.go [hunk 1]
```diff
@@ -20,22 +22,70 @@ import (
...
 
-	if len(args) > 1 {
-		repos = args[1:]
-	} else {
+	// Determine default report file based on current timestamp; for more info see https://pkg.go.dev/time#pkg-constants
+	reportFileDefault := fmt.Sprintf("report-%s.csv", time.Now().Format("20060102150405"))
+
+	// Configure flags for command
+	cmd.Flags().StringSliceVarP(&cmdFlags.reposExclude, "exclude", "e", []string{}, "Repositories to exclude from report")
+	cmd.Flags().StringVarP(&cmdFlags.reportFile, "output-file", "o", reportFileDefault, "Name of file to write CSV report")
```
Comment (andyfeller) [inline cmd/root.go:80]: Might want to enhance the usage message to mention this is auto generated 🤷

File: cmd/root.go [hunk 2]
```diff
@@ -62,7 +112,7 @@ func runCmd(args []string, g Getter, out io.Writer) error {
 
 	if len(repoExcludes) > 0 {
 		sort.Strings(repoExcludes)
-		sugar.Debugf("Excluding repos", "repos", repoExcludes)
+		zap.S().Debugf("Excluding repos", "repos", repoExcludes)
```
Comment (andyfeller) [inline cmd/root.go:115]: For posterity: I really don't want to bother passing loggers around throughout code as it feels unnecessary and a philosophical difference of opinion.  So these changes have been made to simplify the logging initialization and usage to be global loggers.

File: cmd/root.go [hunk 3]
```diff
@@ -187,55 +219,12 @@ func runCmd(args []string, g Getter, out io.Writer) error {
...
-
-func init() {
-	rootCmd.Flags().StringSliceVarP(&repoExcludes, "exclude", "e", []string{}, "Repositories to exclude from report")
-	rootCmd.Flags().StringVarP(&outputFile, "output-file", "o", "", "Name of file to write CSV report, defaults to stdout")
-
-	logger, _ := zap.NewDevelopment()
-	defer logger.Sync()
-	sugar = logger.Sugar()
-}
-
```
Comment (andyfeller) [inline cmd/root.go:238]: These changes are a bit muddy given the others as I had difficulty of initializing the command's flags with the current structure much less help make the code more unit testable later.  The other changes in this PR were as minimal as I could make given where I was at the time.

**Review by andyfeller — COMMENTED** [review]
Closes #2 #3
